image: node:lts

stages:
    - setup
    - test
    - deploy
    - deploy-qa
    - i18n-upgrade-app
    - i18n-to-crowdin

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

variables:
    NODE_OPTIONS: --max-old-space-size=4096

before_script:
 - apt-get -y update
 - apt-get install -y gawk rsync
 - 'which ssh-agent || apt-get -y install openssh-client'
 - eval $(ssh-agent -s)
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
 - git config --global user.email $GIT_CI_EMAIL
 - git config --global user.name $GIT_CI_USERNAME
 - git config --global url."https://".insteadOf git://
 - mkdir ~/.ssh 2> /dev/null
 - |
   cat <<EOF > ~/.ssh/config
   Host github.com
       Hostname ssh.github.com
       User git
       Port 443
       ProxyCommand connect-proxy -H $http_proxy %h %p
   EOF
 - ssh-keyscan -t rsa ${CI_SERVER_HOST} > ~/.ssh/known_hosts
 ## ssh-keyscan doesn't support proxies so we can't fetch the fingerprint online
 - |
   cat <<EOF >> ~/.ssh/known_hosts
   # ssh.github.com:443 SSH-2.0-babeld-2e9d163d
   [ssh.github.com]:443 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
   EOF
 - cat ~/.ssh/config
 - git remote -v
 - git clone "$CI_SCRIPTS_GIT" --depth 1 ci-scripts
 - ls -l

setup:
    stage: setup
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh install-app --remote "$APP_GIT"
    artifacts:
        expire_in: 7 days
        paths:
            - node_modules/
            - src/app/config.ts
            - .env
            - webapp-bundle.tar.gz
            - .gitconfig
            - appConfig.json

lint:
    stage: test
    tags:
        - experimental
    script:
        - npm run lint
        - npm run i18n:validate
        - npm run i18n:validate:context

i18n-upgrade-app:
    stage: i18n-upgrade-app
    tags:
        - dind
    script:
        - ./ci-scripts/prepare-ci.sh i18n upgrade-app --limit "$I18N_APPROVED"
    when: manual

i18n-to-crowdin:
    stage: i18n-to-crowdin
    tags:
        - experimental
    script:
        - ./ci-scripts/prepare-ci.sh i18n to-crowdin
    when: manual

deploy:
    stage: deploy
    tags:
        - experimental
    script:
        - ./ci-scripts/prepare-ci.sh install-app-remote
        - ./ci-scripts/prepare-ci.sh deploy-app --branch "$BRANCH_DEPLOY" --api "$API_DEPLOY"
    when: manual

deploy-qa:
    stage: deploy-qa
    tags:
        - experimental
    script:
        - ./ci-scripts/prepare-ci.sh install-app-remote --update-lock
        - ./ci-scripts/prepare-ci.sh deploy-app --branch "$BRANCH_DEPLOY_QA" --api "$API_DEPLOY"
    when: manual

variables:
    APP_GIT: git@github.com:ProtonMail/proton-drive.git
